### ISSUE TITLE
Cannot delete round

### ISSUE THREAD

**Issue by juliabeltrao** [JakobReiter/Tabbie2#26]
I cannot delete a created but not published round (https://www.tabbie.org/helsinki-open--/outround/544) using the Delete Round button.

**Comment by juliabeltrao** [comment]
Link to error page https://www.tabbie.org/helsinki-open--/outround/delete/544

**Comment by rscoates** [comment]
This is because deleting a round doesn't actually remove the motion tags, so there's a foreign key constraint. Will work on this.

**Comment by rscoates** [comment]
This will be in the next release.
