### ISSUE TITLE
Switch adjudicators crashes if one adjudicator not in a panel

### ISSUE THREAD

**Issue by czlee** [JakobReiter/Tabbie2#34]
Error below happens if you try to swap adjudicators where one adjudicator is not currently assigned to a panel. One might expect this to crash (though I was hoping it would swap an inactive adjudicator for an active one), but flagging in case we'd like to make it fail more gracefully.

It currently shows a debug page, here's the offending line:

Trying to get property of non-object
1. in /var/www/virtual/tabbie/tabbie2/tabbie2.git/frontend/controllers/RoundController.php at line 396

``` php
            ])->orderBy(["panel_id" => SORT_DESC])->one();
            $b_in_panel = AdjudicatorInPanel::find()->joinWith("panel")->where([
                "adjudicator_id" => $b->id,
                "panel.used" => 1,
            ])->orderBy(["panel_id" => SORT_DESC])->one();

            $temp = $a_in_panel->panel_id;
            $temp_pos = $a_in_panel->function;
            $a_in_panel->panel_id = $b_in_panel->panel_id;   // <------ CRASHES HERE
            $a_in_panel->function = $b_in_panel->function;
            $b_in_panel->panel_id = $temp;
            $b_in_panel->function = $temp_pos;

            if ($a_in_panel->validate() && $b_in_panel->validate()) {
                if ($a_in_panel->save() && $b_in_panel->save())
                    Yii::$app->session->addFlash("success", Yii::t("app", "Adjudicator {n1} and {n2} switched", [
                        "n1" => $a->getName(),
                        "n2" => $b->getName(),
```

**Comment by rscoates** [comment]
Hmmmm. I've used this constantly to swap inactive for active adjudicators, so I've never seen this error. Will look into it.

**Comment by czlee** [comment]
I tried again just now and couldn't reproduce this error. I do, however, find a different issue, where on some attempts the adjudicators do not switch, regardless of whether they are both already paired in. It's reproducible in the sense that if I try multiple times it happens a majority of the time, but I can't (easily) spot a pattern that makes it reliably reproducible enough to allow diagnosis. Would you like me to close this issue and then open a new issue for this, if I find a pattern?

**Comment by rscoates** [comment]
If you have a specific tournament, I'll write a test for my local server on that backup, and see what I can find.

**Comment by czlee** [comment]
Still can't reproduce the crashing part, so will close as unreproducible and re-open if I ever hit it again. Will open a new issue for switching adjudicators not working.
