### ISSUE TITLE
Add panellists to the Round Info page

### ISSUE THREAD

**Issue by philipbelesky** [JakobReiter/Tabbie2#37]
Apologies for the open ended feature request. I also don't have a dev environment working atm where I can replicate things so I'm adding this with 100% certainty that this already isn't the case and I've misunderstood something.

Anyway, the round information page is super useful for identifying your room and teams, however (from what I can tell) it does not list your panellists. At the point adjudicators often rely on this page (if they cannot easily view the main draw) not knowing who your panel is can be an issue in terms of knowing when to start a debate and identifying which panellists are trainees etc.

**Comment by JakobReiter** [comment]
I like that - one would just have to add the information here:
https://github.com/JakobReiter/Tabbie2/blob/master/tabbie2.git/frontend/views/tournament/_view_debateinfo.php

**Comment by rscoates** [comment]
Yeah, this is just obviously a good idea. I'll prioritise this.

**Comment by rscoates** [comment]
This will be in the next update.
