### ISSUE TITLE
Error when trying to mark team as 'Swing Team' in 'Create Time'

### ISSUE THREAD

**Issue by jessicayung** [JakobReiter/Tabbie2#44]
After clicking 'Create' on 'Create Team' ('Swing Team' ticked, no error otherwise):
<img width="1009" alt="screenshot" src="https://cloud.githubusercontent.com/assets/11069586/24295434/988c3c5e-1092-11e7-9c82-62e0cf2a96b3.png">
Get error:
<img width="1113" alt="screenshot" src="https://cloud.githubusercontent.com/assets/11069586/24295414/8924871c-1092-11e7-8574-ddb2e633dc8e.png">
<img width="1129" alt="screenshot" src="https://cloud.githubusercontent.com/assets/11069586/24295418/8cdab5f2-1092-11e7-971d-ceddd2a02f74.png">

<img width="1089" alt="screenshot" src="https://cloud.githubusercontent.com/assets/11069586/24295420/8fa0391a-1092-11e7-8c30-5236120d7e4a.png">
<img width="1132" alt="screenshot" src="https://cloud.githubusercontent.com/assets/11069586/24295421/8fb23e44-1092-11e7-97a9-30165170390a.png">

**Comment by rscoates** [comment]
This is because you don't have any speakers in the team. All teams need speakers. The "non-object" is the speakers.
