### ISSUE TITLE
Feedback entry and ballot entry does not work.

### ISSUE THREAD

**Issue by MLEGOL** [JakobReiter/Tabbie2#50]
We are having a very big problem with feedback. Adjudicators cannot submit feedback and they cannot even register ballot scores.

**Comment by rscoates** [comment]
We need more information than this. What is the error? When is it happening? What do they see instead?

**Comment by rscoates** [comment]
Having looked at your tournament (assuming it is the same tournament as yesterday), it appears that you have made an outround before you have completed the inrounds. This could be causing the error.

**Comment by MLEGOL** [comment]
No, it was round 1. It was a test. We are using CND 2017 now. Here is a screenshot of the error.

**Comment by MLEGOL** [comment]
![errorcnd](https://user-images.githubusercontent.com/29866789/27833856-1e439ca0-609a-11e7-8b76-caf388e8fd45.png)

**Comment by rscoates** [comment]
I'm sorry. I'm very confused. You have said that the error is happening on CND 2017, but that screenshot is coming from CND RONDA CERO, no?

**Comment by MLEGOL** [comment]
Yes, because I want to make sure it doesn't happen for this round. We just drew the first round.

**Comment by rscoates** [comment]
And no-one can do feedback yet?

**Comment by MLEGOL** [comment]
Not yet. Round isn't over. Just started. But I want to make sure debaters, chairs and wings can submit feedback after this round.

**Comment by MLEGOL** [comment]
Also, for the Mexican circuit we want to do a cleaning of universities because we have double registries and that makes it hard.

**Comment by MLEGOL** [comment]
Can we be sure the error doesn't happen?

**Comment by rscoates** [comment]
I think it will be safe. The error has occurred from a very specific combination of data, so we should be okay.
