### ISSUE TITLE
Feedback and Ballot entry doesn't work

### ISSUE THREAD

**Issue by MLEGOL** [JakobReiter/Tabbie2#52]
This doesn't work for any of the judges, chairs or debaters that want to access rounds and submit ballots.

**Comment by rscoates** [comment]
As I said yesterday, we need more information than this. What is the error? When is it happening? What do they see instead?

If this is the same issue as yesterday, please do not open a new issue.

**Comment by MLEGOL** [comment]
It's a different issue. They see code.

**Comment by rscoates** [comment]
I'm afraid that 'code' does not give us quite enough information to have a look at it. What code are they seeing? 

It is possible that the tournament that you created with real users to 'test' Tabbie2 was so corrupted that you may have corrupted their accounts. If that is the case, I'm afraid I won't be able to fix this until the weekend at the earliest.

**Comment by MLEGOL** [comment]
No, this is not a test tournament. This is the real tournament, and we are only using real rounds. The issue is the judges are not able to submit feedback I'll have them screenshot it so I can show it to you.

**Comment by rscoates** [comment]
As far as I can see, you created some kind of test tournament with a very corrupted structure. If you registered real adjudicators and speakers into that tournament, it is possible that their accounts are attempting to access the real tournament when they log in, and the corruptions are causing the error. If that is the case, then I'm afraid I can't help.

**Comment by MLEGOL** [comment]
The real tournament is CND 2017; which is where users are not being able to submit round results and/or feedback.

**Comment by rscoates** [comment]
I'm aware of that. If the same users are registered in the test tournament, then you may have corrupted their accounts. However, unless I see a screenshot, I cannot help, and I am just speculating.

**Comment by rscoates** [comment]
Can I assume that this has fixed itself?

**Comment by MLEGOL** [comment]
![error 05 07](https://user-images.githubusercontent.com/29866789/27870861-9e06c096-6169-11e7-89ed-8f28ff0bfeb3.jpg)

**Comment by MLEGOL** [comment]
That is what happens when users try to access it. How did I create a test tournament and not a real one? The issue has, unfortunately, not fixed itself.

**Comment by rscoates** [comment]
CND RONDA CERO appears to be a test tournament - in it, the Tab team created a new inround after outrounds had been created. It is quite likely that this is causing the errors.

**Comment by MLEGOL** [comment]
That is not the tournament we are using. There is a second tournament only called CND 2017. That is the one causing errors. Is the other tournamnet "CND RONDA CERO" causing issues?

**Comment by MLEGOL** [comment]
If so, can "CND RONDA CERO" be deleted? Keeping "CND 2017" which is the national tournament?

**Comment by rscoates** [comment]
I have closed CND RONDA CERO. Let me know if that fixes the problem.

**Comment by MLEGOL** [comment]
![img-20170705-wa0003](https://user-images.githubusercontent.com/29866789/27871976-f2a3eb76-616c-11e7-93ab-73aeaf78a798.jpg)

**Comment by MLEGOL** [comment]
No, the issue persists.

**Comment by rscoates** [comment]
Okay, I'm afraid I won't be able to fix it now. 

My best guess is that the problem is due to these adjudicators being in RONDA CERO, which is severely corrupted, since I have never seen this problem before, and all of these adjudicators were in that tournament.

I will try and look at it this weekend, but until then, please just use paper ballots.
