### ISSUE TITLE
Novice-listed teams not ranked as novice on the Speaker Tab

### ISSUE THREAD

**Issue by pktwum96** [JakobReiter/Tabbie2#88]
After importing teams from CSV, I updated the status of certain teams to novice teams. After the first round, the Team Tab correctly displays these teams as novice. However, the Speaker Tab does not correctly display the status of these speakers as novices. Please refer to the images attached.

Also, some teams may have only one novice speaker. Is there any way to reflect that in the speaker tab?

**Comment by rscoates** [comment]
Hi Kofi,

I’m on the road, so replying by email. I believe that “Novice” is a language status. You should make yourself (as tab director) a language officer also - then you should be able to see the menu to alter these.

Richard

**Comment by pktwum96** [comment]
Thank you very much. Solved the issue
